name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - id: deploy
        uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}

      - id: test
        run: curl "${{ steps.deploy.outputs.url }}"
